In [ ]:
import yaml
import argparse
import logging
from pathlib import Path
import pandas as pd

# Import your custom paths and the new feature engineering orchestrator
from src import paths
from src.barter.pipeline_features import generate_all_features

In [ ]:
clean_deals_path = paths.INTERIM_DATA_DIR / 'BARTER_DEALS_CLEAN.parquet'
raw_apps_path = paths.RAW_DATA_DIR / 'BARTER_DEAL_APPLICATIONS.parquet'
processed_output_path = paths.PROCESSED_DATA_DIR / 'BARTER_DEALS_FEATURES.parquet'

In [16]:
df_apps = pd.read_parquet(raw_apps_path)

In [17]:
df_apps

,legacy_location_id,deal_id,creator_id,rescheduling_deal_application_id,schedule_date,application_status,cancelled_at,cancelled_by,cancelled_by_user_id,cancellation_reason,...,email_address_partners,registered_at_partners,subscription_status_partners,subscription_start_date_partners,subscription_end_date_partners,deals_count_partners,live_deals_count_partners,locations_count_partners,company_size_partners,worked_with_creators_partners
0,335,019689e3-9b82-00c8-52df-2e22979a06ee,8162,<NA>,2024-04-12 00:00:00+00:00,rejected,NaT,<NA>,NaN,<NA>,...,haleigh.feest@anonymized.getbarter.com,2024-02-15 14:31:26.387130+00:00,active,2024-02-15 14:31:21+00:00,2026-03-16 14:31:21+00:00,2.0,0.0,2.0,<NA>,<NA>
1,335,019689e3-9b82-00c8-52df-2e22979a06ee,7787,<NA>,2024-03-26 00:00:00+00:00,cancelled,NaT,<NA>,NaN,<NA>,...,haleigh.feest@anonymized.getbarter.com,2024-02-15 14:31:26.387130+00:00,active,2024-02-15 14:31:21+00:00,2026-03-16 14:31:21+00:00,2.0,0.0,2.0,<NA>,<NA>
2,335,019689e3-9b82-00c8-52df-2e22979a06ee,7827,<NA>,2024-05-29 00:00:00+00:00,accepted,NaT,<NA>,NaN,<NA>,...,haleigh.feest@anonymized.getbarter.com,2024-02-15 14:31:26.387130+00:00,active,2024-02-15 14:31:21+00:00,2026-03-16 14:31:21+00:00,2.0,0.0,2.0,<NA>,<NA>
3,335,019689e3-9b82-00c8-52df-2e22979a06ee,358,<NA>,2024-07-19 00:00:00+00:00,accepted,NaT,<NA>,NaN,<NA>,...,haleigh.feest@anonymized.getbarter.com,2024-02-15 14:31:26.387130+00:00,active,2024-02-15 14:31:21+00:00,2026-03-16 14:31:21+00:00,2.0,0.0,2.0,<NA>,<NA>
4,335,019689e3-9b82-00c8-52df-2e22979a06ee,343,<NA>,2024-05-20 00:00:00+00:00,accepted,NaT,<NA>,NaN,<NA>,...,haleigh.feest@anonymized.getbarter.com,2024-02-15 14:31:26.387130+00:00,active,2024-02-15 14:31:21+00:00,2026-03-16 14:31:21+00:00,2.0,0.0,2.0,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269729,102,019689e4-4bc6-00c8-6ff0-06aca342b058,1577,<NA>,2024-06-29 00:00:00+00:00,finished,NaT,<NA>,NaN,<NA>,...,marlene@anonymized.getbarter.com,2023-10-06 14:09:42.860289+00:00,active,2026-02-17 11:16:02+00:00,2027-02-17 11:31:14+00:00,4.0,1.0,1.0,<NA>,<NA>
269730,102,019689e4-4bc6-00c8-6ff0-06aca342b058,1577,<NA>,2024-07-06 00:00:00+00:00,finished,NaT,<NA>,NaN,<NA>,...,marlene@anonymized.getbarter.com,2023-10-06 14:09:42.860289+00:00,active,2026-02-17 11:16:02+00:00,2027-02-17 11:31:14+00:00,4.0,1.0,1.0,<NA>,<NA>
269731,<NA>,019b359e-7880-00c8-ba13-e73e44044ea9,36953,<NA>,2025-12-22 23:00:00+00:00,accepted,NaT,<NA>,NaN,<NA>,...,watsica.jaiden@anonymized.getbarter.com,2025-12-04 15:26:35.524300+00:00,active,2025-12-19 08:01:56+00:00,2026-03-24 18:39:37+00:00,2.0,1.0,1.0,xs,True
269732,<NA>,019b6abb-9953-00c8-168a-f649e05f64ba,34252,<NA>,NaT,accepted,NaT,<NA>,NaN,<NA>,...,watsica.jaiden@anonymized.getbarter.com,2025-12-04 15:26:35.524300+00:00,active,2025-12-19 08:01:56+00:00,2026-03-24 18:39:37+00:00,2.0,1.0,1.0,xs,True
269733,<NA>,019c707e-037c-00c8-61f7-9b57883ee7c2,97,<NA>,NaT,rejected,2026-02-20 18:48:00.519918+00:00,partner,476.0,,...,marlene@anonymized.getbarter.com,2023-10-06 14:09:42.860289+00:00,active,2026-02-17 11:16:02+00:00,2027-02-17 11:31:14+00:00,4.0,1.0,1.0,<NA>,<NA>

In [4]:
with open('src/configs/config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [ ]:
feature_config = config['analyses']['barter_deals'].get(
    'feature_engineering', {})

In [9]:
df_features = generate_all_features(
    deals_path=clean_deals_path,
    apps_path=raw_apps_path,
    output_path=processed_output_path,
    config=feature_config
)

In [10]:
df_features

,applicants_applications_count,content_types,deal_id,main_image,min_social_media_followers,deal_tags,live_since,first_application_at,last_application_at,company_locations,...,text_word_count,title_word_count,company_location_id,apps_after_7_days,online_eligible_last_week,online_eligible_last_month,physical_active_creators_7d_50km,physical_active_creators_30d_50km,global_active_last_month,global_active_last_week
0,48,"[{'id': 21, 'name': 'Fashion', 'slug': 'Dress'}]",019689e2-1a1f-00c8-81a2-3615a353cd8a,uploads/deals/019689e2-1a92-ffff-a0eb-541b6d69...,50000,None,2023-09-07 09:48:51.484123,2023-09-21 07:03:29.872132,2023-11-14 13:49:25.049111,None,...,117,3,019bb11c-a564-015f-0589-70719678b33b,0,0.0,0.0,0,0,NaN,NaN
1,0,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019689e2-20d4-00c8-4ceb-afb69afa57dc,uploads/deals/019689e2-22bf-ffff-2928-8defbeb7...,2500,None,2023-09-07 10:59:58.899412,NaT,NaT,"[{""id"": ""01KERHT9V405FZ6ENY98QN966E"", ""name"": ...",...,56,9,<NA>,0,0.0,0.0,0,0,NaN,NaN
2,11,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019689e2-23f5-00c8-7750-d15e1f1a744c,uploads/deals/019689e2-2455-ffff-5cf8-c43410f2...,2500,None,2023-09-07 11:00:41.904181,2023-09-21 10:28:27.631503,2023-10-21 12:33:21.687587,"[{""id"": ""01KERHT9V405FZ6ENY98QN966E"", ""name"": ...",...,56,9,019bb11d-2764-015f-f33a-be4a2f5498ce,0,0.0,0.0,0,0,NaN,NaN
3,94,"[{'id': 21, 'name': 'Fashion', 'slug': 'Dress'}]",019689e2-2c11-00c8-f8af-acf5689b167d,uploads/deals/019689e2-2c72-ffff-cd7f-96378b9e...,50000,None,2023-09-08 07:58:15.205196,2023-09-24 12:19:34.069689,2023-11-20 14:17:29.180717,None,...,117,3,019bb11c-a564-015f-0589-70719678b33b,0,0.0,0.0,0,0,NaN,NaN
4,95,"[{'id': 21, 'name': 'Fashion', 'slug': 'Dress'}]",019689e2-2e21-00c8-a03d-e9a97e2a0245,uploads/deals/019689e2-2ec9-ffff-64be-c11c16f5...,50000,None,2023-09-08 08:02:29.330473,2023-09-15 12:42:26.000081,2023-11-15 11:56:08.045898,None,...,117,3,019bb11c-a564-015f-0589-70719678b33b,1,0.0,0.0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6423,2,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019c0b54-a139-00c8-6c0f-67d89c75632c,uploads/deals/019c0b58-380f-ffff-4d40-98dd9764...,1500,None,2026-01-29 20:01:14.400677,2026-01-29 21:05:15.863441,2026-01-30 06:19:24.501434,None,...,1,5,<NA>,2,541.0,1148.0,0,0,1178.0,550.0
6424,25,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019c0b5a-464e-00c8-762c-376fc87682da,uploads/deals/019c0b5b-a1a5-ffff-481e-2544725d...,5000,None,2026-01-29 20:05:04.885661,2026-01-29 20:12:56.888284,2026-01-30 06:55:05.359563,None,...,1,6,<NA>,25,541.0,1148.0,0,0,1178.0,550.0
6425,1,"[{'id': 20, 'name': 'Beauty', 'slug': 'Heart'}]",019c0bd3-6842-00c8-a7b2-dfa4df49d243,uploads/deals/019c0bce-ee0a-ffff-1c58-3cef5947...,5000,None,2026-01-29 22:15:30.192439,2026-01-29 22:56:35.286760,2026-01-29 22:56:35.286760,None,...,1,3,<NA>,1,487.0,1029.0,0,0,1178.0,550.0
6426,3,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",019c2920-e1cf-00c8-86b7-30ddb43064d3,uploads/deals/019c2920-ab62-ffff-5a76-c5271c5a...,1500,None,2026-02-04 14:49:45.672146,2026-02-04 14:58:55.555753,2026-02-04 14:58:55.555753,None,...,29,6,<NA>,1,232.0,779.0,0,0,1124.0,315.0
6427,0,"[{'id': 20, 'name': 'Beauty', 'slug': 'Heart'}...",019c57e7-0650-00c8-a60e-680036aa2e06,uploads/deals/019c57e6-b3f3-ffff-c9e2-2aecaf84...,5000,None,2026-02-13 16:48:04.378345,NaT,NaT,None,...,2,8,<NA>,0,0.0,663.0,0,0,955.0,0.0