In [1]:
from src.utils import generate_content_id

In [2]:
from datasets import load_dataset
import pandas as pd

data_files = {
    "train": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_train.json",
    "validation": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_valid.json",
    "test": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_test.json"
}

ds = load_dataset("json", data_files=data_files)
ratings = pd.DataFrame(ds["train"])


# ratings = load_dataset("McGill-NLP/feedbackQA")["train"]
# ratings = pd.DataFrame(ratings)

ratings["review_1"] = ratings["rating"].apply(lambda x: x[0])
ratings["explanation_1"] = ratings["feedback"].apply(lambda x: x[0])
ratings["review_2"] = ratings["rating"].apply(lambda x: x[1])
ratings["explanation_2"] = ratings["feedback"].apply(lambda x: x[1])
# ratings = ratings.drop(columns=["feedback"])

# Map scores to numeric values
conversion_dict = {"Excellent": 4, "Acceptable": 3,
                   "Could be Improved": 2, "Bad": 1}
ratings["score_1"] = ratings["review_1"].map(conversion_dict)
ratings["score_2"] = ratings["review_2"].map(conversion_dict)


ratings['answer'] = ratings['passage'].apply(
    lambda x: x['reference']['section_content'])

id_columns = ['question', 'answer']
# ratings['input_id'] = ratings.apply(lambda row: generate_content_id(row, id_columns), axis=1)

ratings.groupby("score_1").first()

,question,passage,feedback,rating,domain,review_1,explanation_1,review_2,explanation_2,score_2,answer
score_1,,,,,,,,,,,
1,How do I get help finding a job?,"{'passage_id': 126, 'reference': {'page_title'...",[Talks about tax credits for businesses that h...,"[Bad, Acceptable]",Australia,Bad,Talks about tax credits for businesses that hi...,Acceptable,"This answer discusses the Employment Fund, whi...",3,To further assist job seekers to prepare for a...
2,If I am in Australia on a worker holiday marke...,"{'passage_id': 581, 'reference': {'page_title'...","[Answer is about Working Holiday Makers, but d...","[Could be Improved, Acceptable]",Australia,Could be Improved,"Answer is about Working Holiday Makers, but do...",Acceptable,Answer is rather cut and dry but is also a lit...,3,No. Existing arrangements for specified work w...
3,Do immigration detention centers have proper PPE?,"{'passage_id': 220, 'reference': {'page_title'...",[Claims it monitors PPE levels in the immigran...,"[Acceptable, Acceptable]",Australia,Acceptable,Claims it monitors PPE levels in the immigrant...,Acceptable,This gives a general answer to the question bu...,3,PPE levels are being closely monitored to ensu...
4,How do I get help finding a job?,"{'passage_id': 140, 'reference': {'page_title'...",[Has a link to detailed information about gove...,"[Excellent, Could be Improved]",Australia,Excellent,Has a link to detailed information about gover...,Could be Improved,"This answer provides a link for job searches, ...",2,If you are a current job seeker or participant...

In [ ]:
# ratings[['question', 'answer', 'review_1', 'explanation_1', 'review_2',
#          'explanation_2']][:500].to_csv('FeedbackQA_ratings_500.csv')

In [ ]:
from datasets import load_dataset
import pandas as pd

data_files = {
    "train": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_train.json",
    "validation": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_valid.json",
    "test": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_test.json"
}

ds = load_dataset("json", data_files=data_files)
ratings = pd.DataFrame(ds[["train"]])


# ratings = load_dataset("McGill-NLP/feedbackQA")["train"]
# ratings = pd.DataFrame(ratings)

ratings["review_1"] = ratings["rating"].apply(lambda x: x[0])
ratings["explanation_1"] = ratings["feedback"].apply(lambda x: x[0])
ratings["review_2"] = ratings["rating"].apply(lambda x: x[1])
ratings["explanation_2"] = ratings["feedback"].apply(lambda x: x[1])
# ratings = ratings.drop(columns=["feedback"])

# Map scores to numeric values
conversion_dict = {"Excellent": 4, "Acceptable": 3,
                   "Could be Improved": 2, "Bad": 1}
ratings["score_1"] = ratings["review_1"].map(conversion_dict)
ratings["score_2"] = ratings["review_2"].map(conversion_dict)


ratings['answer'] = ratings['passage'].apply(
    lambda x: x['reference']['section_content'])

id_columns = ['question', 'answer']
# ratings['input_id'] = ratings.apply(lambda row: generate_content_id(row, id_columns), axis=1)

ratings.groupby("score_1").first()

KeyError: "Invalid key: ['train', 'validation', 'test']. Please first select a split. For example: `my_dataset_dictionary['train'][['train', 'validation', 'test']]`. Available splits: ['test', 'train', 'validation']"

# Load

In [ ]:
from datasets import load_dataset
import pandas as pd
from src import paths
from src.utils import generate_content_id

In [ ]:


data_files = {
    "train": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_train.json",
    "validation": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_valid.json",
    "test": "https://huggingface.co/datasets/McGill-NLP/feedbackQA/resolve/main/data/feedback_test.json"
}

ds = load_dataset("json", data_files=data_files)
df_train = pd.DataFrame(ds["train"])
df_train['source_file'] = 'train'
df_validation = pd.DataFrame(ds["validation"])
df_validation['source_file'] = 'validation'
df_test = pd.DataFrame(ds["test"])
df_test['source_file'] = 'test'

ratings = pd.concat([df_train, df_validation, df_test])

ratings.to_parquet(paths.RAW_DATA_DIR / 'MCGILL_FEEDBACKQA_V2.parquet')


ratings

,question,passage,feedback,rating,domain,source_file
0,How do I get help finding a job?,"{'passage_id': 140, 'reference': {'page_title'...",[Has a link to detailed information about gove...,"[Excellent, Could be Improved]",Australia,train
1,How do I get help finding a job?,"{'passage_id': 139, 'reference': {'page_title'...","[A link to a job search website is included, a...","[Excellent, Excellent]",Australia,train
2,How do I get help finding a job?,"{'passage_id': 126, 'reference': {'page_title'...",[Talks about tax credits for businesses that h...,"[Bad, Acceptable]",Australia,train
3,If I am in Australia on a worker holiday marke...,"{'passage_id': 581, 'reference': {'page_title'...","[Answer is about Working Holiday Makers, but d...","[Could be Improved, Acceptable]",Australia,train
4,If I am in Australia on a worker holiday marke...,"{'passage_id': 577, 'reference': {'page_title'...",[Discusses pandemic visas. Doesn't mention the...,"[Bad, Could be Improved]",Australia,train
...,...,...,...,...,...,...
1990,How can I access contraception during the COVI...,"{'passage_id': 72, 'reference': {'page_title':...",[This talks about access to contraceptives but...,"[Could be Improved, Bad, Bad]",WHO,test
1991,Is it ok to change my contraception method now?,"{'passage_id': 72, 'reference': {'page_title':...",[This answer relates to the question and thus ...,"[Excellent, Could be Improved, Acceptable]",WHO,test
1992,Is it a requirement for suspected or confirmed...,"{'passage_id': 105, 'reference': {'page_title'...",[This answer does not relate to the original q...,"[Bad, Bad, Bad]",WHO,test
1993,How can food producers make sure the water the...,"{'passage_id': 209, 'reference': {'page_title'...",[There is not a lot of information in this ans...,"[Could be Improved, Could be Improved, Accepta...",WHO,test
1994,Why do we need to stay active during lockdown ...,"{'passage_id': 44, 'reference': {'page_title':...",[This is a direct answer to the question. this...,"[Excellent, Could be Improved, Bad]",WHO,test

# Processing

In [ ]:
ratings = pd.read_parquet(paths.RAW_DATA_DIR / 'MCGILL_FEEDBACKQA_V2.parquet')

ratings["review_1"] = ratings["rating"].apply(lambda x: x[0])
ratings["explanation_1"] = ratings["feedback"].apply(lambda x: x[0])
ratings["review_2"] = ratings["rating"].apply(lambda x: x[1])
ratings["explanation_2"] = ratings["feedback"].apply(lambda x: x[1])
# ratings = ratings.drop(columns=["feedback"])

# Map scores to numeric values
conversion_dict = {"Excellent": 4, "Acceptable": 3,
                   "Could be Improved": 2, "Bad": 1}
ratings["score_1"] = ratings["review_1"].map(conversion_dict)
ratings["score_2"] = ratings["review_2"].map(conversion_dict)


ratings['answer'] = ratings['passage'].apply(
    lambda x: x['reference']['section_content'])

ratings['input_id'] = ratings.apply(
    lambda row: generate_content_id(row, id_columns), axis=1)

In [34]:
ratings.to_parquet(paths.PROCESSED_DATA_DIR / "MCGILL_FEEDBACKQA_V2.parquet")